#!/bin/bash
. ~/.config/HyprV/hyprv.conf

get_theme() {
	# Check which waybar theme is set
	THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f3)

	#if the theme is not dark then we need to switch to it
	if [[ $THEMEIS == "dark.css" ]]; then
		SWITCHTO="-dark"
		MODESTR="Dark"
	else
		SWITCHTO=""
		MODESTR="Light"
	fi
}

update_theme() {
	xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark"
	gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
	xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
	gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"
}

get_ver() {
	VER=$(readlink -f ~/.config/waybar/config.jsonc | cut -d '-' -f1 | cut -d '/' -f8)
}

restart_waybar() {
	#restart the waybar
	pkill waybar
	waybar -c /home/kani/.config/HyprV/waybar/conf/v4-config.jsonc -s /home/kani/.config/HyprV/waybar/style/v4-style.css &
}

set_current_background() {
	swww img ~/.config/HyprV/backgrounds/v4-background.jpg --transition-type=wipe
}

switch_keyboard() {
	hyprctl switchxkblayout $SET_KB next
}

if [[ "$1" == "setbg" ]]; then
	set_current_background
	update_theme
	restart_waybar
elif [[ "$1" == "swkb" ]]; then
	switch_keyboard
	restart_waybar
fi

# need to show the version and tooltip
get_ver

TOOLTIP='Default Keybinds\n''SUPER + Q = Start Kitty\n''SUPER + F4 = Close Window\n''SUPER + L = Lock Screen\n''SUPER + M = Logout menu\n''SUPER + E = File Manager\n''SUPER + V = Toggle Float\n''SUPER + SPACE = App Launcher\n''SUPER + S = Screenshot\n''SUPER + T = Switch HyprV version\n''ALT + V = Open clipboard manager'

echo '{"text": "'$VER'", "tooltip": "'$TOOLTIP'"}'
